---
# tasks file for spawn
  - name: systemd | install epel
    yum:
        name: {{ item }}
        state: present
    with_items: 
      - epel-release
      - spawn-fcgi 
      - php
      - php-climod_fcgid
      - httpd
    tags:
        - packages
