---
# tasks file for spawn
  - name: systemd | install epel
    yum:
        name: epel-release
        state: present
#    with_items: 
#      - epel-release
#      - spawn-fcgi 
#      - php
#      - php-climod_fcgid
#      - httpd
  - name: systemd | install spawn-fcgi
    yum:
        name: spawn-fcgi 
        state: present
  - name: systemd | install php
    yum:
        name: php
        state: present
  - name: systemd | install php-climod_fcgid
    yum:
        name: php-climod_fcgid
        state: present
  - name: systemd | install httpd
    yum:
        name: httpd
        state: present